on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0,4,8,12,16,20 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: apt-get update
        if: startsWith(runner.os, 'Linux')
        run: sudo apt-get update
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21.3' # The Go version to download (if necessary) and use.
      - uses: cedx/setup-hashlink@v4.0.1
      - name: Install lix
        run: npm i lix -g
      - name: Run lix
        run: npx lix download
      - name: Download go2hx lib
        run: npx haxelib git go2hx https://github.com/go2hx/go2hx
      - name: Setup go2hx
        run: npx haxelib run go2hx build
      - name: extraParams gen
        run: npx haxelib run go2hx extraParams
      - name: cat extraParams
        run: cat extraParams.hxml
      - name: haxelib setup go2hxlibs
        run: haxelib dev go2hxlibs .
      - name: Run unicode example
        run: cd examples && haxe unicode.hxml
      - name: Build
        run: npx haxe build.hxml 1 0
      - uses: stefanzweifel/git-auto-commit-action@v4
        continue-on-error: true
        with:
          commit_message: update libs
